#define BLOOD_PERFUSION_SAFE    0.85
#define BLOOD_PERFUSION_OKAY    0.75
#define BLOOD_PERFUSION_BAD     0.60
#define BLOOD_PERFUSION_SURVIVE 0.40

#define BLOOD_PRESSURE_LCRITICAL 50
#define BLOOD_PRESSURE_L2BAD 65
#define BLOOD_PRESSURE_LBAD 80
#define BLOOD_PRESSURE_NORMAL 120
#define BLOOD_PRESSURE_HBAD 140
#define BLOOD_PRESSURE_H2BAD 160
#define BLOOD_PRESSURE_HCRITICAL 180

#define RYTHME_NORM 1
#define RYTHME_AFIB 2
#define RYTHME_AFIB_RR 3
#define RYTHME_VFIB 4
#define RYTHME_ASYSTOLE 5